name: 🐍 Generate Snake Animation

on:
  schedule: # Exécuter toutes les 12 heures
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build:
    name: Générer le serpent
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Générer l'animation du serpent
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }} # Votre pseudo GitHub
          outputs: dist/github-contribution-grid-snake2.svg
          snake_color: "blue" # Changez la couleur du serpent si vous voulez

      - name: Publier sur GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # Enregistre les fichiers générés dans la branche "output"
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Clé secrète pour autoriser l'action
