name: Générer un serpent GitHub

on:
  schedule:
    - cron: "*/30 * * * *" # Exécuter toutes les 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/actions/generate@v3
        with:
          github_user_name: "${{ github.repository_owner }}"
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
