name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Exécute toutes les 12 heures
  workflow_dispatch:

jobs:
  build:
    name: Générer le serpent
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Vérifier le contenu du dossier
        run: ls -la

      - name: Générer l'animation du serpent
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: user99x
          outputs: dist/snake.svg
          snake_color: "blue"

      - name: Vérifier si le fichier a été créé
        run: ls -la dist/

      - name: Publier sur GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
